spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Java-Techie-jt/cloud-config-server

server:
  port: 9196

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  
    
microservice:
 Payment-Service:
   endpoints:
    endpoints:
      endPoint:
          - http://Payment-Service/payment/doPayment  

Order-Service:
   endpoints:
    endpoints:
      endPoint:
          - http://Payment-Service/payment/doPayment           
